name: Bug report
description: Create a report to help us improve
labels:
  - needs triage
body:

  - type: textarea
    attributes:
      label: What happens?
      description: A short, clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: |
        Please provide steps to reproduce the behavior, preferably a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Please adhere the following guidelines:

        * Format the code and the output as [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) using triple backticks:

          ````
          ```
          CODE HERE
          ```
          ````
        * Remove all prompts from the scripts. This include DuckDB's 'D' prompt and Python's `>>>` prompt. Removing these prompts makes reproduction attempts quicker.
        * Make sure that the script and its outputs are provided in separate code blocks.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Environment"
  - type: input
    attributes:
      label: "OS:"
      placeholder: e.g., Linux, MacOS, etc.
      description: Please include operating system version and architecture (e.g., aarch64, x86_64, etc.).
    validations:
      required: true
  - type: input
    attributes:
      label: "pg_ducklake Version:"
      placeholder: e.g., commit hash
    validations:
      required: true
  - type: input
    attributes:
      label: "Postgres Version:"
      placeholder: e.g., 18
    validations:
      required: true
  - type: input
    attributes:
      label: "Hardware:"
      placeholder: If your issue is performance-related, please include information on your CPU and memory.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Are you using pg_ducklake Docker, or the extension standalone?
      options:
        - pg_ducklake Docker Image
        - pg_ducklake extension standalone
    validations:
      required: true
